"""
write_to_template.py

Fills TFG_DataProfiling_Template_v1.xlsx (NetSuite sheet) with mock profiling
data generated by netsuite_mock_data.py.

Usage:
    python src/write_to_template.py \
        --template TFG_DataProfiling_Template_v1.xlsx \
        --output output/TFG_DataProfiling_Template_NetSuite_Filled.xlsx
"""

import argparse
import random
import sqlite3
from copy import copy
from datetime import date, timedelta
from pathlib import Path

from openpyxl import load_workbook
from openpyxl.cell.cell import MergedCell
from openpyxl.utils import get_column_letter

from netsuite_mock_data import TABLES

# Path to the persisted mock DB (one level above src/)
DB_PATH = Path(__file__).parent.parent / "netsuite_mock.db"

# Some tables use a different name in the DB than in the TABLES dict
DB_TABLE_MAP = {
    "TRANSACTION": "ns_transaction",
}

# ---------------------------------------------------------------------------
# Mock metadata per table
# ---------------------------------------------------------------------------
TABLE_META = {
    "TRANSACTION": {
        "purpose": "Records all financial transactions (invoices, payments, journals)",
        "grain": "One row = one transaction header",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "TRANSACTION, INVOICE, JOURNAL_ENTRY",
        "date_field": "trandate",
    },
    "TRANSACTIONLINE": {
        "purpose": "Line-level detail for each transaction",
        "grain": "One row = one transaction line item",
        "pk": "id + line (composite)",
        "domain": "D5 – Financials",
        "entities": "TRANSACTION_LINE",
        "date_field": "trandate",
    },
    "CUSTOMER": {
        "purpose": "Master record for all customers / billing entities",
        "grain": "One row = one customer",
        "pk": "id (surrogate)",
        "domain": "D1 – Customers & Locations",
        "entities": "CUSTOMER",
        "date_field": "datecreated",
    },
    "VENDOR": {
        "purpose": "Master record for all vendors and suppliers",
        "grain": "One row = one vendor",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "VENDOR",
        "date_field": "datecreated",
    },
    "ITEM": {
        "purpose": "Product and service catalog items",
        "grain": "One row = one item / SKU",
        "pk": "id (surrogate)",
        "domain": "D2 – Contracts & Revenue",
        "entities": "ITEM",
        "date_field": "lastmodifieddate",
    },
    "EMPLOYEE": {
        "purpose": "HR employee master used for approvals and assignments",
        "grain": "One row = one employee",
        "pk": "id (surrogate)",
        "domain": "D3 – Workforce",
        "entities": "EMPLOYEE",
        "date_field": "datecreated",
    },
    "ACCOUNT": {
        "purpose": "Chart of accounts for GL posting",
        "grain": "One row = one GL account",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "GL_ACCOUNT",
        "date_field": "lastmodifieddate",
    },
    "SUBSIDIARY": {
        "purpose": "Legal entities / subsidiaries within NetSuite OneWorld",
        "grain": "One row = one subsidiary",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "SUBSIDIARY",
        "date_field": "lastmodifieddate",
    },
    "DEPARTMENT": {
        "purpose": "Cost centre / department classification",
        "grain": "One row = one department",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "DEPARTMENT",
        "date_field": "lastmodifieddate",
    },
    "SALESORDER": {
        "purpose": "Sales orders linked to customers and items",
        "grain": "One row = one sales order header",
        "pk": "id (surrogate)",
        "domain": "D2 – Contracts & Revenue",
        "entities": "SALES_ORDER",
        "date_field": "trandate",
    },
    "PURCHASEORDER": {
        "purpose": "Purchase orders raised against vendors",
        "grain": "One row = one purchase order header",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "PURCHASE_ORDER",
        "date_field": "trandate",
    },
}

# Section A rows (1-indexed in the sheet)
SECTION_A = {
    7:  "SuiteQL REST API",
    8:  "Yes",
    9:  "PASS",
    10: "Fabric Tables",
    11: "2025-03-01",
    12: "Daily",
    13: "=TOTAL_ROWS rows across 10 key tables",
    14: "2020-01-01 to 2025-03-01",
    15: "NetSuite SuiteQL 2024.1",
    16: "Minor null rate on subsidiary_id in TRANSACTION",
    17: "TBD – awaiting TFG confirmation",
    18: "Scheduled for 2025-03-15",
}

# Section B: block layout constants
# Each block is BLOCK_HEIGHT rows tall, starting at BLOCK_START_ROW.
# Offsets within a block (relative to block base row):
#   +0  = table header label
#   +2  = view/table name row
#   +5  = row count row
#   +14 = field-level quality start
#   +22 = referential integrity start
BLOCK_HEIGHT = 26
BLOCK_START_ROW = 23
# How many blocks the template physically contains (we insert rows for extras)
TEMPLATE_BLOCK_COUNT = 3
# First row immediately after the last template block
TEMPLATE_AFTER_BLOCKS_ROW = BLOCK_START_ROW + TEMPLATE_BLOCK_COUNT * BLOCK_HEIGHT  # 101

# Original Section D / E positions (before any row insertion)
ORIGINAL_FRESHNESS_HEADER_ROW = 114
ORIGINAL_FRESHNESS_START_ROW = 115
ORIGINAL_FRESHNESS_MAX_ROWS = 7

ORIGINAL_SECTION_E = {
    124: "GREEN",
    125: "1. Null subsidiary_id on ~2% of TRANSACTION rows\n"
         "2. DEPARTMENT row count lower than expected\n"
         "3. No direct FK from SALESORDER to CONTRACT",
    126: "Fabric Tables (pipeline confirmed PASS)",
    127: "CUSTOMER and VENDOR joinable on entity_id; EMPLOYEE separate",
    128: "None — pipeline accessible",
    129: "Proceed to field-level profiling for TRANSACTION and CUSTOMER",
    130: "Confirm fiscal year definition used in trandate filters",
}

# Column definitions per table: (col_name, col_type)
# Stats (null%, distinct, min, max, notes, RAG) are queried from the DB at runtime.
TABLE_COLUMNS = {
    "CUSTOMER":      [("id","INTEGER"),("companyname","VARCHAR"),("email","VARCHAR"),
                      ("datecreated","DATETIME"),("subsidiary_id","INTEGER")],
    "VENDOR":        [("id","INTEGER"),("companyname","VARCHAR"),("email","VARCHAR"),
                      ("datecreated","DATETIME"),("subsidiary_id","INTEGER")],
    "ITEM":          [("id","INTEGER"),("itemid","VARCHAR"),("salesdescription","VARCHAR"),
                      ("rate","DECIMAL"),("lastmodifieddate","DATETIME")],
    "TRANSACTION":   [("id","INTEGER"),("tranid","VARCHAR"),("type","VARCHAR"),
                      ("trandate","DATETIME"),("entity","INTEGER"),
                      ("subsidiary_id","INTEGER"),("amount","DECIMAL")],
    "EMPLOYEE":      [("id","INTEGER"),("entityid","VARCHAR"),("firstname","VARCHAR"),
                      ("lastname","VARCHAR"),("email","VARCHAR"),
                      ("datecreated","DATETIME"),("subsidiary_id","INTEGER")],
    "ACCOUNT":       [("id","INTEGER"),("acctnumber","VARCHAR"),("acctname","VARCHAR"),
                      ("accttype","VARCHAR"),("subsidiary_id","INTEGER")],
    "SUBSIDIARY":    [("id","INTEGER"),("name","VARCHAR")],
    "DEPARTMENT":    [("id","INTEGER"),("name","VARCHAR"),("subsidiary_id","INTEGER")],
    "SALESORDER":    [("id","INTEGER"),("tranid","VARCHAR"),("trandate","DATE"),
                      ("entity","INTEGER"),("amount","DECIMAL"),("status","VARCHAR")],
    "PURCHASEORDER": [("id","INTEGER"),("tranid","VARCHAR"),("trandate","DATE"),
                      ("entity","INTEGER"),("amount","DECIMAL"),("status","VARCHAR")],
}

# FK relationship definitions per table: (fk_col, parent_logical_name, parent_pk)
# Orphan counts and percentages are queried from the DB at runtime.
TABLE_FK_DEFS = {
    "CUSTOMER":      [("subsidiary_id","SUBSIDIARY","id"),("department_id","DEPARTMENT","id")],
    "VENDOR":        [("subsidiary_id","SUBSIDIARY","id")],
    "ITEM":          [("subsidiary_id","SUBSIDIARY","id"),("department_id","DEPARTMENT","id")],
    "TRANSACTION":   [("entity","CUSTOMER","id"),("subsidiary_id","SUBSIDIARY","id"),
                      ("department_id","DEPARTMENT","id")],
    "EMPLOYEE":      [("subsidiary_id","SUBSIDIARY","id"),("department_id","DEPARTMENT","id")],
    "ACCOUNT":       [("subsidiary_id","SUBSIDIARY","id")],
    "SUBSIDIARY":    [],
    "DEPARTMENT":    [("subsidiary_id","SUBSIDIARY","id")],
    "SALESORDER":    [("entity","CUSTOMER","id"),("subsidiary_id","SUBSIDIARY","id")],
    "PURCHASEORDER": [("entity","VENDOR","id"),("subsidiary_id","SUBSIDIARY","id")],
}

# Section D freshness
FRESHNESS_MAX_ROWS = 10  # all tables

# Section E: Engineer summary (col D).
# Item 1 (key issues) is built dynamically in fill_template using actual counts.
SECTION_E_STATIC = {
    0: "GREEN",
    2: "Fabric Tables (pipeline confirmed PASS)",
    3: "CUSTOMER and VENDOR joinable on entity_id; EMPLOYEE separate",
    4: "None — pipeline accessible",
    5: "Proceed to field-level profiling for TRANSACTION and CUSTOMER",
    6: "Confirm fiscal year definition used in trandate filters",
}
SECTION_E_COL = 4
SECTION_E_ROW_COUNT = len(SECTION_E_STATIC)


# ---------------------------------------------------------------------------
# DB query helpers — all metrics derived from netsuite_mock.db at runtime
# ---------------------------------------------------------------------------

def _db():
    """Open and return a connection to netsuite_mock.db."""
    return sqlite3.connect(DB_PATH)


def query_row_counts(conn) -> dict:
    counts = {}
    for table in TABLES:
        db_table = DB_TABLE_MAP.get(table, table.lower())
        counts[table] = conn.execute(f'SELECT COUNT(*) FROM "{db_table}"').fetchone()[0]
    return counts


def query_field_stats(conn, db_table: str, col: str, total: int):
    """Return (null_pct_str, null_rate, distinct, min_val, max_val) for one column."""
    nulls    = conn.execute(f'SELECT COUNT(*) FROM "{db_table}" WHERE "{col}" IS NULL').fetchone()[0]
    distinct = conn.execute(f'SELECT COUNT(DISTINCT "{col}") FROM "{db_table}"').fetchone()[0]
    mn       = conn.execute(f'SELECT MIN("{col}") FROM "{db_table}"').fetchone()[0]
    mx       = conn.execute(f'SELECT MAX("{col}") FROM "{db_table}"').fetchone()[0]
    null_rate    = nulls / total if total > 0 else 0
    null_pct_str = f"{null_rate * 100:.1f}%"
    return null_pct_str, null_rate, nulls, distinct, mn, mx


def compute_rag(null_rate: float) -> str:
    if null_rate > 0.30:
        return "RED"
    if null_rate >= 0.10:
        return "AMBER"
    return "GREEN"


def compute_notes(col: str, null_rate: float, nulls: int, distinct: int, total: int) -> str:
    if null_rate == 0:
        if distinct == total:
            return "No nulls, no duplicates"
        return f"No nulls; {distinct} distinct value(s)"
    return f"{nulls} null ({null_rate * 100:.1f}%)"


def query_date_range(conn, db_table: str, date_col: str) -> str:
    """Return 'MIN – MAX' for date_col, or 'N/A' if column absent."""
    cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{db_table}")').fetchall()]
    if date_col not in cols:
        return "N/A"
    row = conn.execute(f'SELECT MIN("{date_col}"), MAX("{date_col}") FROM "{db_table}"').fetchone()
    if row and row[0] and row[1]:
        return f"{row[0]} – {row[1]}"
    return "N/A"


def query_freshness(conn, db_table: str, date_field: str) -> dict:
    """Return freshness dict with actual MAX(date_field) from the DB."""
    from datetime import datetime as _dt
    cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{db_table}")').fetchall()]
    if date_field not in cols:
        return {"date_field": date_field, "most_recent": "N/A",
                "load_date": "N/A", "lag": "N/A", "acceptable": "N/A", "notes": "No date column"}
    most_recent_str = conn.execute(f'SELECT MAX("{date_field}") FROM "{db_table}"').fetchone()[0]
    load_date = date.today()
    if most_recent_str:
        mr = _dt.strptime(most_recent_str[:10], "%Y-%m-%d").date()
        lag = (load_date - mr).days
        return {"date_field": date_field, "most_recent": str(mr),
                "load_date": str(load_date), "lag": lag,
                "acceptable": "Yes" if lag <= 3 else "No",
                "notes": "Within SLA" if lag <= 3 else f"{lag}-day lag – investigate"}
    return {"date_field": date_field, "most_recent": "N/A",
            "load_date": str(load_date), "lag": "N/A", "acceptable": "N/A", "notes": "No data"}


def query_fk_stats(conn, child_db: str, fk_col: str, parent_db: str, parent_pk: str):
    """Return (orphan_count, orphan_pct_str, impact, rag) for one FK relationship."""
    total   = conn.execute(
        f'SELECT COUNT(*) FROM "{child_db}" WHERE "{fk_col}" IS NOT NULL'
    ).fetchone()[0]
    orphans = conn.execute(
        f'SELECT COUNT(*) FROM "{child_db}" '
        f'WHERE "{fk_col}" IS NOT NULL '
        f'AND "{fk_col}" NOT IN (SELECT "{parent_pk}" FROM "{parent_db}")'
    ).fetchone()[0]
    orphan_rate = orphans / total if total > 0 else 0
    orphan_pct  = f"{orphan_rate * 100:.1f}%"
    impact = "None" if orphans == 0 else ("Low" if orphan_rate < 0.02 else "Medium")
    rag    = "GREEN" if orphans == 0 else ("AMBER" if orphan_rate < 0.05 else "RED")
    return orphans, orphan_pct, impact, rag


def copy_block_format(ws, source_idx: int, target_idx: int, n_cols: int = 12):
    """Copy cell values AND styles from the source block to the target block
    row-for-row, column-for-column.  This propagates both the static row labels
    (e.g. 'Table / view name', 'Business purpose') and all visual formatting.
    Data writes that happen afterwards will overwrite the value cells (col D)
    with the actual table-specific content.
    Call this AFTER unmerging so every cell is a plain Cell object.
    """
    source_base = BLOCK_START_ROW + source_idx * BLOCK_HEIGHT
    target_base = BLOCK_START_ROW + target_idx * BLOCK_HEIGHT
    for row_off in range(BLOCK_HEIGHT):
        for col in range(1, n_cols + 1):
            src = ws.cell(row=source_base + row_off, column=col)
            tgt = ws.cell(row=target_base + row_off, column=col)
            tgt.value         = src.value          # copy static labels too
            tgt.font          = copy(src.font)
            tgt.fill          = copy(src.fill)
            tgt.border        = copy(src.border)
            tgt.alignment     = copy(src.alignment)
            tgt.number_format = src.number_format


def safe_write(ws, row: int, col: int, value):
    """Write value to a cell (assumes all merges have been removed beforehand)."""
    ws.cell(row=row, column=col, value=value)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def fill_template(template_path: str, output_path: str):
    conn = _db()
    counts = query_row_counts(conn)
    tables = list(counts.keys())
    n      = len(tables)
    total_rows = sum(counts.values())

    wb = load_workbook(template_path)
    ws = wb["NetSuite"]

    # Unmerge everything so every cell is writable
    for mr in list(ws.merged_cells.ranges):
        ws.unmerge_cells(str(mr))

    # Propagate block-1 formatting + labels to blocks 4–N
    for slot_idx in range(TEMPLATE_BLOCK_COUNT, n):
        copy_block_format(ws, source_idx=0, target_idx=slot_idx)

    # --- Section A ---
    for row_num, value in SECTION_A.items():
        if isinstance(value, str) and "=TOTAL_ROWS" in value:
            value = value.replace("=TOTAL_ROWS", f"{total_rows:,}")
        safe_write(ws, row_num, 4, value)

    # --- Section B: one block per table ---
    for slot_idx, table in enumerate(tables):
        db_table    = DB_TABLE_MAP.get(table, table.lower())
        meta        = TABLE_META.get(table, {})
        count       = counts[table]
        date_field  = meta.get("date_field", "")

        base        = BLOCK_START_ROW + slot_idx * BLOCK_HEIGHT
        hdr_row     = base
        view_row    = base + 2
        cnt_row     = base + 5
        field_start = base + 14
        fk_start    = base + 22

        safe_write(ws, hdr_row,      2, f"Table {slot_idx + 1}: {table}")
        safe_write(ws, view_row,     4, table)
        safe_write(ws, view_row + 1, 4, meta.get("purpose", ""))
        safe_write(ws, view_row + 2, 4, meta.get("grain", ""))
        safe_write(ws, cnt_row,      4, count)
        safe_write(ws, cnt_row + 1,  4, query_date_range(conn, db_table, date_field) if date_field else "N/A")
        safe_write(ws, cnt_row + 2,  4, meta.get("pk", ""))
        safe_write(ws, cnt_row + 3,  4, "PASS" if count > 0 else "FAIL")
        safe_write(ws, cnt_row + 4,  4, meta.get("domain", ""))
        safe_write(ws, cnt_row + 5,  4, meta.get("entities", ""))
        safe_write(ws, cnt_row + 6,  4, "GREEN")

        # Field-Level Quality — stats queried from DB
        for fi, (col, col_type) in enumerate(TABLE_COLUMNS.get(table, [])):
            null_pct_str, null_rate, nulls, distinct, mn, mx = query_field_stats(
                conn, db_table, col, count
            )
            notes = compute_notes(col, null_rate, nulls, distinct, count)
            rag   = compute_rag(null_rate)
            r = field_start + fi
            ws.cell(row=r, column=2, value=col)
            ws.cell(row=r, column=3, value=col_type)
            ws.cell(row=r, column=4, value=null_pct_str)
            ws.cell(row=r, column=5, value=distinct)
            ws.cell(row=r, column=6, value=mn)
            ws.cell(row=r, column=7, value=mx)
            ws.cell(row=r, column=8, value=notes)
            ws.cell(row=r, column=9, value=rag)

        # Referential Integrity — orphan counts queried from DB
        for ki, (fk_col, parent_logical, parent_pk) in enumerate(TABLE_FK_DEFS.get(table, [])):
            parent_db = DB_TABLE_MAP.get(parent_logical, parent_logical.lower())
            orphans, orphan_pct, impact, rag = query_fk_stats(
                conn, db_table, fk_col, parent_db, parent_pk
            )
            r = fk_start + ki
            ws.cell(row=r, column=2, value=fk_col)
            ws.cell(row=r, column=3, value=parent_logical)
            ws.cell(row=r, column=4, value=parent_pk)
            ws.cell(row=r, column=5, value=orphans)
            ws.cell(row=r, column=6, value=orphan_pct)
            ws.cell(row=r, column=7, value=impact)
            ws.cell(row=r, column=8, value=rag)

    # --- Section D: Data Freshness — actual MAX(date_field) from DB ---
    last_block_base = BLOCK_START_ROW + (n - 1) * BLOCK_HEIGHT
    freshness_start = last_block_base + BLOCK_HEIGHT + 2
    safe_write(ws, freshness_start - 1, 2, "Section D – Data Freshness")
    for i, table in enumerate(tables):
        db_table   = DB_TABLE_MAP.get(table, table.lower())
        date_field = TABLE_META.get(table, {}).get("date_field", "")
        f = query_freshness(conn, db_table, date_field) if date_field else {
            "date_field": "N/A", "most_recent": "N/A",
            "load_date": str(date.today()), "lag": "N/A",
            "acceptable": "N/A", "notes": "No date field defined"
        }
        r = freshness_start + i
        safe_write(ws, r, 2, table)
        safe_write(ws, r, 3, f["date_field"])
        safe_write(ws, r, 4, f["most_recent"])
        safe_write(ws, r, 5, f["load_date"])
        safe_write(ws, r, 6, f["lag"])
        safe_write(ws, r, 7, f["acceptable"])
        safe_write(ws, r, 8, f["notes"])

    # --- Section E: Engineer Summary — issues derived from actual DB queries ---
    section_e_start = freshness_start + n + 2
    safe_write(ws, section_e_start - 1, 2, "Section E – Engineer Summary")

    def _null_count(tbl, col):
        db = DB_TABLE_MAP.get(tbl, tbl.lower())
        return conn.execute(f'SELECT COUNT(*) FROM "{db}" WHERE "{col}" IS NULL').fetchone()[0]

    issues = []
    for tbl, col, label in [
        ("CUSTOMER",      "email",         "CUSTOMER email"),
        ("VENDOR",        "email",         "VENDOR email"),
        ("EMPLOYEE",      "email",         "EMPLOYEE email"),
        ("ITEM",          "salesdescription", "ITEM salesdescription"),
        ("ITEM",          "rate",          "ITEM rate"),
    ]:
        nc = _null_count(tbl, col)
        total = counts[tbl]
        if nc > 0:
            issues.append(f"{label}: {nc} null ({nc/total*100:.1f}%)")

    issues_text = "\n".join(f"{i+1}. {msg}" for i, msg in enumerate(issues)) if issues \
        else "No significant null issues detected"

    section_e_content = {**SECTION_E_STATIC, 1: issues_text}
    for offset, value in section_e_content.items():
        safe_write(ws, section_e_start + offset, SECTION_E_COL, value)

    conn.close()
    wb.save(output_path)
    print(f"Filled template saved to: {output_path}")
    print(f"\nSection B  — {n} table block(s) filled")
    print(f"Section D  — {n} tables in Data Freshness  (rows {freshness_start}–{freshness_start + n - 1})")
    print(f"Section E  — Engineer Summary  (rows {section_e_start}–{section_e_start + SECTION_E_ROW_COUNT - 1})")


def parse_args():
    parser = argparse.ArgumentParser(description="Fill TFG Data Profiling Template")
    parser.add_argument("--template", required=True, help="Path to template .xlsx")
    parser.add_argument("--output", required=True, help="Path for output .xlsx")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    fill_template(args.template, args.output)
