"""
write_to_template.py

Fills TFG_DataProfiling_Template_v1.xlsx (NetSuite sheet) with mock profiling
data generated by netsuite_mock_data.py.

Usage:
    python src/write_to_template.py \
        --template TFG_DataProfiling_Template_v1.xlsx \
        --output output/TFG_DataProfiling_Template_NetSuite_Filled.xlsx
"""

import argparse
import random
from datetime import date, timedelta

from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

from netsuite_mock_data import TABLES

# ---------------------------------------------------------------------------
# Mock metadata per table
# ---------------------------------------------------------------------------
TABLE_META = {
    "TRANSACTION": {
        "purpose": "Records all financial transactions (invoices, payments, journals)",
        "grain": "One row = one transaction header",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "TRANSACTION, INVOICE, JOURNAL_ENTRY",
        "date_field": "trandate",
    },
    "TRANSACTIONLINE": {
        "purpose": "Line-level detail for each transaction",
        "grain": "One row = one transaction line item",
        "pk": "id + line (composite)",
        "domain": "D5 – Financials",
        "entities": "TRANSACTION_LINE",
        "date_field": "trandate",
    },
    "CUSTOMER": {
        "purpose": "Master record for all customers / billing entities",
        "grain": "One row = one customer",
        "pk": "id (surrogate)",
        "domain": "D1 – Customers & Locations",
        "entities": "CUSTOMER",
        "date_field": "datecreated",
    },
    "VENDOR": {
        "purpose": "Master record for all vendors and suppliers",
        "grain": "One row = one vendor",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "VENDOR",
        "date_field": "datecreated",
    },
    "ITEM": {
        "purpose": "Product and service catalog items",
        "grain": "One row = one item / SKU",
        "pk": "id (surrogate)",
        "domain": "D2 – Contracts & Revenue",
        "entities": "ITEM",
        "date_field": "lastmodifieddate",
    },
    "EMPLOYEE": {
        "purpose": "HR employee master used for approvals and assignments",
        "grain": "One row = one employee",
        "pk": "id (surrogate)",
        "domain": "D3 – Workforce",
        "entities": "EMPLOYEE",
        "date_field": "datecreated",
    },
    "ACCOUNT": {
        "purpose": "Chart of accounts for GL posting",
        "grain": "One row = one GL account",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "GL_ACCOUNT",
        "date_field": "lastmodifieddate",
    },
    "SUBSIDIARY": {
        "purpose": "Legal entities / subsidiaries within NetSuite OneWorld",
        "grain": "One row = one subsidiary",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "SUBSIDIARY",
        "date_field": "lastmodifieddate",
    },
    "DEPARTMENT": {
        "purpose": "Cost centre / department classification",
        "grain": "One row = one department",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "DEPARTMENT",
        "date_field": "lastmodifieddate",
    },
    "SALESORDER": {
        "purpose": "Sales orders linked to customers and items",
        "grain": "One row = one sales order header",
        "pk": "id (surrogate)",
        "domain": "D2 – Contracts & Revenue",
        "entities": "SALES_ORDER",
        "date_field": "trandate",
    },
    "PURCHASEORDER": {
        "purpose": "Purchase orders raised against vendors",
        "grain": "One row = one purchase order header",
        "pk": "id (surrogate)",
        "domain": "D5 – Financials",
        "entities": "PURCHASE_ORDER",
        "date_field": "trandate",
    },
}

# Section A rows (1-indexed in the sheet)
SECTION_A = {
    7:  "SuiteQL REST API",
    8:  "Yes",
    9:  "PASS",
    10: "Fabric Tables",
    11: "2025-03-01",
    12: "Daily",
    13: "~10,500 rows across 10 key tables",
    14: "2020-01-01 to 2025-03-01",
    15: "NetSuite SuiteQL 2024.1",
    16: "Minor null rate on subsidiary_id in TRANSACTION",
    17: "TBD – awaiting TFG confirmation",
    18: "Scheduled for 2025-03-15",
}

# Section B: (header_row, view_name_row, row_count_row, field_start_row, fk_start_row)
BLOCK_SLOTS = [
    (23, 25, 28, 37, 45),
    (49, 51, 54, 63, 71),
    (75, 77, 80, 89, 97),
]

# Field-level quality data per table: (name, type, null_pct, distinct, min, max, notes, rag)
TABLE_FIELDS = {
    "CUSTOMER": [
        ("id",           "INTEGER",  "0%",   "~500",  1,            9999,          "PK – no nulls",                "GREEN"),
        ("companyname",  "VARCHAR",  "2%",   "~490",  "Aaron Inc",  "Zurich LLC",  "2% blank names",               "AMBER"),
        ("email",        "VARCHAR",  "15%",  "~420",  None,         None,          "15% null – not mandatory",     "AMBER"),
        ("datecreated",  "DATETIME", "0%",   "~480",  "2020-01-03", "2025-02-28",  "",                             "GREEN"),
        ("subsidiary_id","INTEGER",  "1%",   5,       1,            5,             "1% null – FK risk",            "AMBER"),
    ],
    "VENDOR": [
        ("id",           "INTEGER",  "0%",   "~200",  1,            9999,          "PK – no nulls",                "GREEN"),
        ("companyname",  "VARCHAR",  "0%",   "~200",  "A1 Supply",  "Zurich Parts","",                             "GREEN"),
        ("email",        "VARCHAR",  "20%",  "~160",  None,         None,          "20% null",                     "AMBER"),
        ("datecreated",  "DATETIME", "0%",   "~195",  "2020-01-05", "2025-02-25",  "",                             "GREEN"),
        ("subsidiary_id","INTEGER",  "3%",   5,       1,            5,             "3% null",                      "AMBER"),
    ],
    "ITEM": [
        ("id",              "INTEGER",  "0%",  "~1000", 1,            99999,         "PK – no nulls",                "GREEN"),
        ("itemid",          "VARCHAR",  "0%",  "~1000", "ITEM-0001",  "ITEM-9999",   "",                             "GREEN"),
        ("salesdescription","VARCHAR",  "8%",  "~920",  None,         None,          "8% null descriptions",         "AMBER"),
        ("rate",            "DECIMAL",  "5%",  "~800",  0.01,         99999.99,      "5% null – check item type",    "AMBER"),
        ("lastmodifieddate","DATETIME", "0%",  "~950",  "2020-01-01", "2025-03-01",  "",                             "GREEN"),
    ],
}

# Referential integrity checks per table: (fk_field, ref_table, ref_field, orphan_count, orphan_pct, impact, rag)
TABLE_FK_CHECKS = {
    "CUSTOMER": [
        ("subsidiary_id", "SUBSIDIARY", "id", 5,  "1.0%", "Low",  "GREEN"),
        ("salesrep_id",   "EMPLOYEE",   "id", 12, "2.4%", "Low",  "AMBER"),
    ],
    "VENDOR": [
        ("subsidiary_id", "SUBSIDIARY", "id", 6, "3.0%", "Low",  "AMBER"),
        ("currency_id",   "CURRENCY",   "id", 0, "0.0%", "None", "GREEN"),
    ],
    "ITEM": [
        ("subsidiary_id", "SUBSIDIARY", "id", 0, "0.0%", "None", "GREEN"),
        ("department_id", "DEPARTMENT", "id", 3, "0.3%", "Low",  "GREEN"),
    ],
}

# Section D: Data Freshness header is row 114; data rows 115–121 (7 slots before Section E)
FRESHNESS_START_ROW = 115
FRESHNESS_MAX_ROWS = 7

# Section E: Engineer summary col D starts at row 124
SECTION_E = {
    124: "GREEN",
    125: "1. Null subsidiary_id on ~2% of TRANSACTION rows\n"
         "2. DEPARTMENT row count lower than expected\n"
         "3. No direct FK from SALESORDER to CONTRACT",
    126: "Fabric Tables (pipeline confirmed PASS)",
    127: "CUSTOMER and VENDOR joinable on entity_id; EMPLOYEE separate",
    128: "None — pipeline accessible",
    129: "Proceed to field-level profiling for TRANSACTION and CUSTOMER",
    130: "Confirm fiscal year definition used in trandate filters",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def mock_row_counts() -> dict:
    return {t: base + random.randint(-50, 50) for t, base in TABLES.items()}


def mock_date_range(table: str) -> str:
    end = date(2025, 3, 1)
    start = date(2020, 1, 1)
    return f"{start} – {end}"


def mock_freshness(table: str) -> dict:
    most_recent = date(2025, 3, 1) - timedelta(days=random.randint(0, 5))
    load_date = date(2025, 3, 2)
    lag = (load_date - most_recent).days
    return {
        "date_field": TABLE_META.get(table, {}).get("date_field", "lastmodifieddate"),
        "most_recent": str(most_recent),
        "load_date": str(load_date),
        "lag": lag,
        "acceptable": "Yes" if lag <= 3 else "No",
        "notes": "Within SLA" if lag <= 3 else "Investigate load delay",
    }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def safe_write(ws, row: int, col: int, value):
    """Write value to a cell, resolving merged ranges to their top-left cell."""
    coord = f"{get_column_letter(col)}{row}"
    for mr in ws.merged_cells.ranges:
        if coord in mr:
            ws.cell(row=mr.min_row, column=mr.min_col, value=value)
            return
    ws.cell(row=row, column=col, value=value)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def fill_template(template_path: str, output_path: str):
    wb = load_workbook(template_path)
    ws = wb["NetSuite"]
    counts = mock_row_counts()

    tables = list(counts.keys())

    # --- Section A ---
    for row_num, value in SECTION_A.items():
        safe_write(ws, row_num, 4, value)

    # --- Section B: fill the 3 template block slots ---
    for slot_idx, (hdr_row, view_row, cnt_row, field_start, fk_start) in enumerate(BLOCK_SLOTS):
        if slot_idx >= len(tables):
            break
        table = tables[slot_idx]
        meta = TABLE_META.get(table, {})
        count = counts[table]

        safe_write(ws, hdr_row, 2, f"Table {slot_idx + 1}: {table}")
        safe_write(ws, view_row, 4, table)
        safe_write(ws, view_row + 1, 4, meta.get("purpose", ""))
        safe_write(ws, view_row + 2, 4, meta.get("grain", ""))
        safe_write(ws, cnt_row, 4, count)
        safe_write(ws, cnt_row + 1, 4, mock_date_range(table))
        safe_write(ws, cnt_row + 2, 4, meta.get("pk", ""))
        safe_write(ws, cnt_row + 3, 4, "PASS" if count > 0 else "FAIL")
        safe_write(ws, cnt_row + 4, 4, meta.get("domain", ""))
        safe_write(ws, cnt_row + 5, 4, meta.get("entities", ""))
        safe_write(ws, cnt_row + 6, 4, "GREEN")

        # Field-Level Quality
        for fi, (fname, ftype, null_pct, distinct, fmin, fmax, notes, rag) in enumerate(
            TABLE_FIELDS.get(table, [])
        ):
            r = field_start + fi
            ws.cell(row=r, column=2, value=fname)
            ws.cell(row=r, column=3, value=ftype)
            ws.cell(row=r, column=4, value=null_pct)
            ws.cell(row=r, column=5, value=distinct)
            ws.cell(row=r, column=6, value=fmin)
            ws.cell(row=r, column=7, value=fmax)
            ws.cell(row=r, column=8, value=notes)
            ws.cell(row=r, column=9, value=rag)

        # Referential Integrity Checks
        for ki, (fk_field, ref_table, ref_field, orphan_count, orphan_pct, impact, rag) in enumerate(
            TABLE_FK_CHECKS.get(table, [])
        ):
            r = fk_start + ki
            ws.cell(row=r, column=2, value=fk_field)
            ws.cell(row=r, column=3, value=ref_table)
            ws.cell(row=r, column=4, value=ref_field)
            ws.cell(row=r, column=5, value=orphan_count)
            ws.cell(row=r, column=6, value=orphan_pct)
            ws.cell(row=r, column=7, value=impact)
            ws.cell(row=r, column=8, value=rag)

    # --- Section D: Data Freshness — up to 7 tables (template row limit) ---
    for i, (table, count) in enumerate(list(counts.items())[:FRESHNESS_MAX_ROWS]):
        f = mock_freshness(table)
        r = FRESHNESS_START_ROW + i
        safe_write(ws, r, 2, table)
        safe_write(ws, r, 3, f["date_field"])
        safe_write(ws, r, 4, f["most_recent"])
        safe_write(ws, r, 5, f["load_date"])
        safe_write(ws, r, 6, f["lag"])
        safe_write(ws, r, 7, f["acceptable"])
        safe_write(ws, r, 8, f["notes"])

    # --- Section E: Engineer Summary ---
    for row_num, value in SECTION_E.items():
        safe_write(ws, row_num, 4, value)

    wb.save(output_path)
    print(f"Filled template saved to: {output_path}")
    print(f"\nSection B  — {min(3, len(tables))} table block(s) filled")
    print(f"Section D  — {min(FRESHNESS_MAX_ROWS, len(tables))} tables in Data Freshness")
    print("Section E  — Engineer Summary filled")


def parse_args():
    parser = argparse.ArgumentParser(description="Fill TFG Data Profiling Template")
    parser.add_argument("--template", required=True, help="Path to template .xlsx")
    parser.add_argument("--output", required=True, help="Path for output .xlsx")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    fill_template(args.template, args.output)
